language: scala

services:
   - docker
   
before_install:
  - echo -e "travis_fold:start:neo4j"
  - travis_wait 200 docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 dockernet
  - travis_wait 200 docker run -d --name db -p 7687:7687 --ulimit=nofile=1000000:1000000 --net=dockernet --env=NEO4J_AUTH=neo4j/test --env=NEOREADONLY=false --env=NEO4J_dbms_memory_heap_maxSize=10G --env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes rcourt/docker-neo4j-knowledgebase
  - sleep 90s
  - docker logs db
  - docker network inspect dockernet 
  - echo -e "travis_fold:end:neo4j"


script:
   - sbt "run -io -f -t --usr=neo4j --pwd=test --endpoint=bolt://192.168.0.2:7687 --dataset=Chiang2010  --ontology=resources/support_ont.owl "
   - sbt "run --usr=neo4j --pwd=test --endpoint=bolt://192.168.0.2:7687 --dataset=Ito2013  --ontology=resources/support_ont.owll "
#   - sbt "run --usr=neo4j --pwd=test --endpoint=bolt://192.168.0.2:7687 --dataset=Hampel2015  --ontology=resources/support_ont.owl "
   - sbt "run -t --usr=neo4j --pwd=test --endpoint=bolt://192.168.0.2:7687 --dataset=Jenett2012  --ontology=resources/support_ont.owl "
   - sbt "run -t --usr=neo4j --pwd=test --endpoint=bolt://192.168.0.2:7687 --dataset=CostaJefferis_v3  --ontology=resources/support_ont.owl "

