#services:
#  - docker
  
#script:
#  - docker build -t test-image:test .
#  - docker run -d --name test test-image:test
#  - sleep 2m
#  - docker logs test

language: scala

script:
   - sbt run org.virtualflybrain.neo_kb_2_owl.Main
   - sbt run org.virtualflybrain.neo_kb_2_owl.Main -t --endpoint='http://kb.virtualflybrain.org' dataset='Cachero2010'
   
