#services:
#  - docker
  
#script:
#  - docker build -t test-image:test .
#  - docker run -d --name test test-image:test
#  - sleep 2m
#  - docker logs test

language: scala

script:
   - sbt "run --usr=neo4j --pwd=neo4j --endpoint=bolt://kb.virtualflybrain.org:7688 --dataset=Chiang2010  --ontology=resources/fbbt-simple.owl "
 

