#services:
#  - docker
  
#script:
#  - docker build -t test-image:test .
#  - docker run -d --name test test-image:test
#  - sleep 2m
#  - docker logs test

language: scala

services:
   - docker
   
before_install:
  - echo -e "travis_fold:start:neo4j"
  - travis_wait 200 docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 dockernet
  - travis_wait 200 docker run -d --name db -p 7687:7687 --ulimit=nofile=1000000:1000000 --net=dockernet --env=NEO4J_AUTH=neo4j/neo4j --env=NEOREADONLY=false --env=NEO4J_dbms_memory_heap_maxSize=10G --env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes rcourt/docker-neo4j-knowledgebase
  - sleep 90s
  - docker logs db
  - echo -e "travis_fold:end:neo4j"


script:
   - sbt "run --usr=neo4j --pwd=neo4j --endpoint=bolt://192.168.0.1:7687 --dataset=Chiang2010  --ontology=resources/fbbt-simple.owl "
 

